# Permalinks
permalink:           pretty

# Setup
title:               Pierre Gordon
tagline:             A Software Engineer
description:         '"Sucking at something is the first step to becoming sorta good at something." - Jake from Adventure Time'
url:                 https://pierlon.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Pierre Gordon
  url:               https://pierlon.github.io
  email:             pierregordon@icloud.com

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:             pierregordon@icloud.com
  facebook:
  flickr:
  github:            pierlon
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CNAME

# Custom vars
version:             1.0.1
